/* ============================================================================
   Fase 1 - Capa de fachada del origen: sinonimos por ambiente
   ----------------------------------------------------------------------------
   Genera los 38 sinonimos del esquema EXT que cubren TODAS las referencias al
   origen encontradas en BD y BD_prod (6485 referencias literales en 153
   archivos se resuelven con estos 38 objetos).

   Se ejecuta con sqlcmd pasando la base de origen del ambiente:
     sqlcmd -S <srv> -d KARDIA -i 01_crear_sinonimos_EXT.sql -v ORIGEN="Quiero_Confianza"
     sqlcmd -S <srv> -d KARDIA -i 01_crear_sinonimos_EXT.sql -v ORIGEN="Quiero_Confianza_shadow"

   El codigo de los procedimientos deja de conocer el nombre de la base: la
   unica diferencia entre ambientes vive en este script. Es tambien el punto
   donde, el dia que salga SAF/Sisde, se apunta al nuevo origen sin tocar los
   245 objetos programables.

   Generado por auditoria/fase1/generar_sinonimos.py - no editar a mano.
   ============================================================================ */
SET NOCOUNT ON;
IF SCHEMA_ID(N'EXT') IS NULL EXEC(N'CREATE SCHEMA EXT');
GO

-- 1329 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_RUBRO_COBRO_X_CREDITO', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_RUBRO_COBRO_X_CREDITO;
CREATE SYNONYM EXT.PR_RUBRO_COBRO_X_CREDITO FOR [$(ORIGEN)].[PR].[PR_RUBRO_COBRO_X_CREDITO];

-- 1039 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_ENCABEZADO_PAGO', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_ENCABEZADO_PAGO;
CREATE SYNONYM EXT.PR_ENCABEZADO_PAGO FOR [$(ORIGEN)].[PR].[PR_ENCABEZADO_PAGO];

-- 813 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_DETALLE_PAGO', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_DETALLE_PAGO;
CREATE SYNONYM EXT.PR_DETALLE_PAGO FOR [$(ORIGEN)].[PR].[PR_DETALLE_PAGO];

-- 809 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_CREDITOS', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_CREDITOS;
CREATE SYNONYM EXT.PR_CREDITOS FOR [$(ORIGEN)].[PR].[PR_CREDITOS];

-- 440 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CG_CATALOGO_X_EMPRESA', N'SN') IS NOT NULL DROP SYNONYM EXT.CG_CATALOGO_X_EMPRESA;
CREATE SYNONYM EXT.CG_CATALOGO_X_EMPRESA FOR [$(ORIGEN)].[CG].[CG_CATALOGO_X_EMPRESA];

-- 332 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_TIPO_CREDITO', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_TIPO_CREDITO;
CREATE SYNONYM EXT.PR_TIPO_CREDITO FOR [$(ORIGEN)].[PR].[PR_TIPO_CREDITO];

-- 316 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_CALCULO_INTERESES_DIA', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_CALCULO_INTERESES_DIA;
CREATE SYNONYM EXT.PR_CALCULO_INTERESES_DIA FOR [$(ORIGEN)].[PR].[PR_CALCULO_INTERESES_DIA];

-- 316 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.BA_CTA_CORRIENTE', N'SN') IS NOT NULL DROP SYNONYM EXT.BA_CTA_CORRIENTE;
CREATE SYNONYM EXT.BA_CTA_CORRIENTE FOR [$(ORIGEN)].[BA].[BA_CTA_CORRIENTE];

-- 273 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CL_PERSONAS_FISICAS', N'SN') IS NOT NULL DROP SYNONYM EXT.CL_PERSONAS_FISICAS;
CREATE SYNONYM EXT.CL_PERSONAS_FISICAS FOR [$(ORIGEN)].[CL].[CL_PERSONAS_FISICAS];

-- 147 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CL_PERSONAS_JURIDICAS', N'SN') IS NOT NULL DROP SYNONYM EXT.CL_PERSONAS_JURIDICAS;
CREATE SYNONYM EXT.CL_PERSONAS_JURIDICAS FOR [$(ORIGEN)].[CL].[CL_PERSONAS_JURIDICAS];

-- 132 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_DEPOSITOS_X_IDENTIFICAR', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_DEPOSITOS_X_IDENTIFICAR;
CREATE SYNONYM EXT.PR_DEPOSITOS_X_IDENTIFICAR FOR [$(ORIGEN)].[PR].[PR_DEPOSITOS_X_IDENTIFICAR];

-- 116 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CL_CLIENTES', N'SN') IS NOT NULL DROP SYNONYM EXT.CL_CLIENTES;
CREATE SYNONYM EXT.CL_CLIENTES FOR [$(ORIGEN)].[CL].[CL_CLIENTES];

-- 106 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_PRIORIDAD_RUBRO_TIPOCRED', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_PRIORIDAD_RUBRO_TIPOCRED;
CREATE SYNONYM EXT.PR_PRIORIDAD_RUBRO_TIPOCRED FOR [$(ORIGEN)].[PR].[PR_PRIORIDAD_RUBRO_TIPOCRED];

-- 87 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_RECLASIFICACION_ETAPA_RIESGO', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_RECLASIFICACION_ETAPA_RIESGO;
CREATE SYNONYM EXT.PR_RECLASIFICACION_ETAPA_RIESGO FOR [$(ORIGEN)].[PR].[PR_RECLASIFICACION_ETAPA_RIESGO];

-- 59 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_RUBRO_X_CREDITO', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_RUBRO_X_CREDITO;
CREATE SYNONYM EXT.PR_RUBRO_X_CREDITO FOR [$(ORIGEN)].[PR].[PR_RUBRO_X_CREDITO];

-- 40 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_CALCULO_MORA_DIA', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_CALCULO_MORA_DIA;
CREATE SYNONYM EXT.PR_CALCULO_MORA_DIA FOR [$(ORIGEN)].[PR].[PR_CALCULO_MORA_DIA];

-- 21 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_DESC_TIPOS_CREDITO', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_DESC_TIPOS_CREDITO;
CREATE SYNONYM EXT.PR_DESC_TIPOS_CREDITO FOR [$(ORIGEN)].[PR].[PR_DESC_TIPOS_CREDITO];

-- 15 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_GARANTIAS_CREDITO', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_GARANTIAS_CREDITO;
CREATE SYNONYM EXT.PR_GARANTIAS_CREDITO FOR [$(ORIGEN)].[PR].[PR_GARANTIAS_CREDITO];

-- 15 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_GARANTIAS', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_GARANTIAS;
CREATE SYNONYM EXT.PR_GARANTIAS FOR [$(ORIGEN)].[PR].[PR_GARANTIAS];

-- 11 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CF_CALENDARIOS', N'SN') IS NOT NULL DROP SYNONYM EXT.CF_CALENDARIOS;
CREATE SYNONYM EXT.CF_CALENDARIOS FOR [$(ORIGEN)].[CF].[CF_CALENDARIOS];

-- 9 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_ORIGEN_FONDOS', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_ORIGEN_FONDOS;
CREATE SYNONYM EXT.PR_ORIGEN_FONDOS FOR [$(ORIGEN)].[PR].[PR_ORIGEN_FONDOS];

-- 8 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PA_PAISES', N'SN') IS NOT NULL DROP SYNONYM EXT.PA_PAISES;
CREATE SYNONYM EXT.PA_PAISES FOR [$(ORIGEN)].[PA].[PA_PAISES];

-- 6 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CL_DIR_CLIENTES', N'SN') IS NOT NULL DROP SYNONYM EXT.CL_DIR_CLIENTES;
CREATE SYNONYM EXT.CL_DIR_CLIENTES FOR [$(ORIGEN)].[CL].[CL_DIR_CLIENTES];

-- 6 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PA_PROVINCIAS', N'SN') IS NOT NULL DROP SYNONYM EXT.PA_PROVINCIAS;
CREATE SYNONYM EXT.PA_PROVINCIAS FOR [$(ORIGEN)].[PA].[PA_PROVINCIAS];

-- 6 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PA_DISTRITOS', N'SN') IS NOT NULL DROP SYNONYM EXT.PA_DISTRITOS;
CREATE SYNONYM EXT.PA_DISTRITOS FOR [$(ORIGEN)].[PA].[PA_DISTRITOS];

-- 6 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CL_V_INFORMACION_SALDOFAVORTRANSACCION', N'SN') IS NOT NULL DROP SYNONYM EXT.CL_V_INFORMACION_SALDOFAVORTRANSACCION;
CREATE SYNONYM EXT.CL_V_INFORMACION_SALDOFAVORTRANSACCION FOR [$(ORIGEN)].[CL].[CL_V_INFORMACION_SALDOFAVORTRANSACCION];

-- 5 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CL_ID_CLIENTES', N'SN') IS NOT NULL DROP SYNONYM EXT.CL_ID_CLIENTES;
CREATE SYNONYM EXT.CL_ID_CLIENTES FOR [$(ORIGEN)].[CL].[CL_ID_CLIENTES];

-- 4 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CL_V_INFORMACION_SALDOFAVORCLIENTE', N'SN') IS NOT NULL DROP SYNONYM EXT.CL_V_INFORMACION_SALDOFAVORCLIENTE;
CREATE SYNONYM EXT.CL_V_INFORMACION_SALDOFAVORCLIENTE FOR [$(ORIGEN)].[CL].[CL_V_INFORMACION_SALDOFAVORCLIENTE];

-- 3 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PA_CANTONES', N'SN') IS NOT NULL DROP SYNONYM EXT.PA_CANTONES;
CREATE SYNONYM EXT.PA_CANTONES FOR [$(ORIGEN)].[PA].[PA_CANTONES];

-- 3 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CL_SALDO_A_FAVOR', N'SN') IS NOT NULL DROP SYNONYM EXT.CL_SALDO_A_FAVOR;
CREATE SYNONYM EXT.CL_SALDO_A_FAVOR FOR [$(ORIGEN)].[CL].[CL_SALDO_A_FAVOR];

-- 2 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_INF_PROYECTO', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_INF_PROYECTO;
CREATE SYNONYM EXT.PR_INF_PROYECTO FOR [$(ORIGEN)].[PR].[PR_INF_PROYECTO];

-- 2 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CF_CATALOGO_ENC', N'SN') IS NOT NULL DROP SYNONYM EXT.CF_CATALOGO_ENC;
CREATE SYNONYM EXT.CF_CATALOGO_ENC FOR [$(ORIGEN)].[CF].[CF_CATALOGO_ENC];

-- 2 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CF_CATALOGO_DET', N'SN') IS NOT NULL DROP SYNONYM EXT.CF_CATALOGO_DET;
CREATE SYNONYM EXT.CF_CATALOGO_DET FOR [$(ORIGEN)].[CF].[CF_CATALOGO_DET];

-- 2 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_INF_RR_X_CREDITO', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_INF_RR_X_CREDITO;
CREATE SYNONYM EXT.PR_INF_RR_X_CREDITO FOR [$(ORIGEN)].[PR].[PR_INF_RR_X_CREDITO];

-- 2 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_RUBRO', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_RUBRO;
CREATE SYNONYM EXT.PR_RUBRO FOR [$(ORIGEN)].[PR].[PR_RUBRO];

-- 1 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PR_CTAS_REFERENCIADAS', N'SN') IS NOT NULL DROP SYNONYM EXT.PR_CTAS_REFERENCIADAS;
CREATE SYNONYM EXT.PR_CTAS_REFERENCIADAS FOR [$(ORIGEN)].[PR].[PR_CTAS_REFERENCIADAS];

-- 1 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.PA_CODIGO_POSTAL', N'SN') IS NOT NULL DROP SYNONYM EXT.PA_CODIGO_POSTAL;
CREATE SYNONYM EXT.PA_CODIGO_POSTAL FOR [$(ORIGEN)].[PA].[PA_CODIGO_POSTAL];

-- 1 referencias en el corpus auditado
IF OBJECT_ID(N'EXT.CL_CONVENIO_X_CLIENTE', N'SN') IS NOT NULL DROP SYNONYM EXT.CL_CONVENIO_X_CLIENTE;
CREATE SYNONYM EXT.CL_CONVENIO_X_CLIENTE FOR [$(ORIGEN)].[CL].[CL_CONVENIO_X_CLIENTE];
GO
